application:
  name: fintech-local
  owner: Robert
  greeter:
    userName: Robert
    morningMessage: Very good morning
    afternoonMessage: Good afternoon
    eveningMessage: Good evening
    nightMessage: Good night
app:
  name: "Fintech"
  value: "val"
  colour: "Red"